openapi: 3.0.3
info:
  title: ''
  version: 0.0.0
paths:
  /login/:
    post:
      operationId: login_create
      description: ''
      tags:
      - login
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          description: No response body
  /polls/:
    get:
      operationId: polls_list
      description: ''
      tags:
      - polls
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Poll'
          description: ''
    post:
      operationId: polls_create
      description: ''
      tags:
      - polls
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Poll'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Poll'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Poll'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
          description: ''
  /polls/{id}/:
    get:
      operationId: polls_retrieve
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this poll.
        required: true
      tags:
      - polls
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
          description: ''
    put:
      operationId: polls_update
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this poll.
        required: true
      tags:
      - polls
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Poll'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Poll'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Poll'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
          description: ''
    patch:
      operationId: polls_partial_update
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this poll.
        required: true
      tags:
      - polls
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PatchedPoll'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/PatchedPoll'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/PatchedPoll'
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poll'
          description: ''
    delete:
      operationId: polls_destroy
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        description: A unique integer value identifying this poll.
        required: true
      tags:
      - polls
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '204':
          description: No response body
  /polls/{id}/choices/:
    get:
      operationId: polls_choices_list
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - polls
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Choice'
          description: ''
    post:
      operationId: polls_choices_create
      description: ''
      parameters:
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - polls
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Choice'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Choice'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Choice'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Choice'
          description: ''
  /polls/{id}/choices/{choice_pk}/vote/:
    post:
      operationId: polls_choices_vote_create
      description: ''
      parameters:
      - in: path
        name: choice_pk
        schema:
          type: integer
        required: true
      - in: path
        name: id
        schema:
          type: integer
        required: true
      tags:
      - polls
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Vote'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/Vote'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Vote'
        required: true
      security:
      - tokenAuth: []
      - cookieAuth: []
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vote'
          description: ''
  /users/:
    post:
      operationId: users_create
      description: ''
      tags:
      - users
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/User'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: ''
components:
  schemas:
    Choice:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        votes:
          type: array
          items:
            $ref: '#/components/schemas/Vote'
        choice_text:
          type: string
          maxLength: 100
        poll:
          type: integer
      required:
      - choice_text
      - id
      - poll
    PatchedPoll:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        choices:
          type: array
          items:
            $ref: '#/components/schemas/Choice'
          readOnly: true
        question:
          type: string
          maxLength: 100
        pub_date:
          type: string
          format: date-time
          readOnly: true
        created_by:
          type: integer
    Poll:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        choices:
          type: array
          items:
            $ref: '#/components/schemas/Choice'
          readOnly: true
        question:
          type: string
          maxLength: 100
        pub_date:
          type: string
          format: date-time
          readOnly: true
        created_by:
          type: integer
      required:
      - choices
      - created_by
      - id
      - pub_date
      - question
    User:
      type: object
      properties:
        username:
          type: string
          description: Required. 150 characters or fewer. Letters, digits and @/./+/-/_
            only.
          pattern: ^[\w.@+-]+$
          maxLength: 150
        email:
          type: string
          format: email
          maxLength: 254
        password:
          type: string
          writeOnly: true
          maxLength: 128
      required:
      - password
      - username
    Vote:
      type: object
      properties:
        id:
          type: integer
          readOnly: true
        choice:
          type: integer
        poll:
          type: integer
        voted_by:
          type: integer
      required:
      - choice
      - id
      - poll
      - voted_by
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: Session
    tokenAuth:
      type: http
      scheme: bearer
      bearerFormat: Token
